# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchOperatorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchOperator(object):
    def setupUi(self, BatchOperator):
        BatchOperator.setObjectName("BatchOperator")
        BatchOperator.setEnabled(True)
        BatchOperator.resize(485, 172)
        BatchOperator.setStyleSheet("* {\n"
"    font-family:\"KaiTi\";\n"
"    font-size:28px;\n"
"    color: #F8F8F2;\n"
"}\n"
"\n"
"*::item:hover {\n"
"    background-color: #474844;\n"
"}\n"
"*::item:selected {\n"
"    background-color: #75715E;\n"
"}\n"
"/* 背景 */\n"
"QWidget {\n"
"    background-color: #202120;\n"
"}\n"
"/* list */\n"
"QListWidget {\n"
"    background-color: #272822;\n"
"    border: none;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"/* table */\n"
"QTableWidget {\n"
"    background-color: #272822;\n"
"    border: none;\n"
"}\n"
"/* 编辑栏 */\n"
"QLineEdit {\n"
"    border: 1px solid #99947c; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    background-color: #414339; /* 背景颜色 */\n"
"    color: #cccccc; /* 文本颜色 */\n"
"    selection-background-color: #646765; /* 选中文本的背景颜色 */\n"
"    selection-color: #cccccc; /* 选中文本的颜色 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #292a28;\n"
"    color: #292a28;\n"
"}\n"
"\n"
"/* table:表头 */\n"
"QHeaderView::section {\n"
"    background-color: #272822;\n"
"}\n"
"/* 按钮 */\n"
"QPushButton {\n"
"    background-color: #75715e;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8d8871;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #8d8871;\n"
"}\n"
"/* 多页Tab */\n"
"QTabBar::tab {\n"
"    background-color: #34352f;\n"
"    margin-right:1px;\n"
"    margin-left:1px;\n"
"    width:150px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #272822;\n"
"}\n"
"QTabWidget::pane{\n"
"    border:none;\n"
"}\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #99947c;\n"
"    background-color: #414339;    \n"
"    color: #cccccc; \n"
"    font-size:25px;\n"
"    border-width:2px;/*边框宽度*/\n"
"    padding-left: 5px;/*左侧边距*/\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    border: 1px solid #99947c;\n"
"    background-color: #414339;   \n"
"    selection-background-color: #75715E;   \n"
"}\n"
"\n"
"\n"
"/* 状态条 */\n"
"QStatusBar {\n"
"    background-color: #414339;\n"
"}\n"
"/* 菜单栏 */\n"
"QMenuBar, QMenu {\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"}\n"
"QMenuBar::item:disabled, QMenu::item:disabled {\n"
"    color: #4c4d4b;\n"
"}\n"
"/* 滑动条 */\n"
"QScrollBar:disabled {\n"
"    background: #272822;\n"
"}\n"
"QScrollBar:vertical {\n"
"    width: 8px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    height: 8px;\n"
"}\n"
"QScrollBar::handle { \n"
"    padding: 0;\n"
"    margin: 2px;\n"
"    border-radius: 2px;\n"
"    border: 2px solid palette(midlight);\n"
"    background: palette(midlight);\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    min-height: 20px;\n"
"    min-width: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    min-width: 20px;\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    border-color: palette(light);\n"
"    background: palette(light);\n"
"}\n"
"QScrollBar::handle:pressed {\n"
"    background: palette(highlight);\n"
"    border-color: palette(highlight);\n"
"}\n"
"QScrollBar::add-line , QScrollBar::sub-line {\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(BatchOperator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ins_Label = QtWidgets.QLabel(BatchOperator)
        self.ins_Label.setObjectName("ins_Label")
        self.verticalLayout.addWidget(self.ins_Label)
        self.comboBox = QtWidgets.QComboBox(BatchOperator)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.batchEdit = QtWidgets.QLineEdit(BatchOperator)
        self.batchEdit.setEnabled(True)
        self.batchEdit.setText("")
        self.batchEdit.setObjectName("batchEdit")
        self.verticalLayout.addWidget(self.batchEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.batchRun = QtWidgets.QPushButton(BatchOperator)
        self.batchRun.setObjectName("batchRun")
        self.horizontalLayout.addWidget(self.batchRun)
        self.backup = QtWidgets.QCheckBox(BatchOperator)
        self.backup.setChecked(True)
        self.backup.setObjectName("backup")
        self.horizontalLayout.addWidget(self.backup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BatchOperator)
        QtCore.QMetaObject.connectSlotsByName(BatchOperator)

    def retranslateUi(self, BatchOperator):
        _translate = QtCore.QCoreApplication.translate
        BatchOperator.setWindowTitle(_translate("BatchOperator", "批量增删"))
        self.ins_Label.setText(_translate("BatchOperator", "对过滤后的图像进行批量操作"))
        self.comboBox.setItemText(0, _translate("BatchOperator", "前插"))
        self.comboBox.setItemText(1, _translate("BatchOperator", "后插"))
        self.comboBox.setItemText(2, _translate("BatchOperator", "删除"))
        self.comboBox.setItemText(3, _translate("BatchOperator", "\'(...)\' → \'/(.../)\'"))
        self.comboBox.setItemText(4, _translate("BatchOperator", "\'/(.../)\' → \'(...)\'"))
        self.comboBox.setItemText(5, _translate("BatchOperator", "空格 → 下划线"))
        self.comboBox.setItemText(6, _translate("BatchOperator", "下划线 → 空格"))
        self.batchRun.setText(_translate("BatchOperator", "执行"))
        self.backup.setText(_translate("BatchOperator", "备份标签"))
