# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName("Filter")
        Filter.resize(575, 584)
        Filter.setStyleSheet("* {\n"
"    font-family:\"KaiTi\";\n"
"    font-size:28px;\n"
"    color: #F8F8F2;\n"
"}\n"
"\n"
"*::item:hover {\n"
"    background-color: #474844;\n"
"}\n"
"*::item:selected {\n"
"    background-color: #75715E;\n"
"}\n"
"/* 背景 */\n"
"QWidget {\n"
"    background-color: #202120;\n"
"}\n"
"/* list */\n"
"QListWidget {\n"
"    background-color: #272822;\n"
"    border: none;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"/* table */\n"
"QTableWidget {\n"
"    background-color: #272822;\n"
"    border: none;\n"
"}\n"
"/* table:表头 */\n"
"QHeaderView::section {\n"
"    background-color: #272822;\n"
"}\n"
"/* 按钮 */\n"
"QPushButton {\n"
"    background-color: #75715e;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8d8871;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #8d8871;\n"
"}\n"
"\n"
"/* 多页Tab */\n"
"QTabBar::tab {\n"
"    background-color: #34352f;\n"
"    margin-right:1px;\n"
"    margin-left:1px;\n"
"    width:150px;\n"
"    height:40px;\n"
"\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #272822;\n"
"}\n"
"QTabWidget::pane{\n"
"    border:none;\n"
"}\n"
"/* 状态条 */\n"
"QStatusBar {\n"
"    background-color: #414339;\n"
"}\n"
"/* 菜单栏 */\n"
"QMenuBar, QMenu {\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"}\n"
"QMenuBar::item:disabled, QMenu::item:disabled {\n"
"    color: #4c4d4b;\n"
"}\n"
"/* 滑动条 */\n"
"QScrollBar:disabled {\n"
"    background: #272822;\n"
"}\n"
"QScrollBar:vertical {\n"
"    width: 8px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    height: 8px;\n"
"}\n"
"QScrollBar::handle { \n"
"    padding: 0;\n"
"    margin: 2px;\n"
"    border-radius: 2px;\n"
"    border: 2px solid palette(midlight);\n"
"    background: palette(midlight);\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    min-height: 20px;\n"
"    min-width: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    min-width: 20px;\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    border-color: palette(light);\n"
"    background: palette(light);\n"
"}\n"
"QScrollBar::handle:pressed {\n"
"    background: palette(highlight);\n"
"    border-color: palette(highlight);\n"
"}\n"
"QScrollBar::add-line , QScrollBar::sub-line {\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Filter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tagFilterbutton = QtWidgets.QPushButton(Filter)
        self.tagFilterbutton.setAutoFillBackground(False)
        self.tagFilterbutton.setStyleSheet("QPushButton {\n"
"    background-color: #34352f;\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"    width: 150px;\n"
"    height:40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #272822;\n"
"}")
        self.tagFilterbutton.setCheckable(True)
        self.tagFilterbutton.setChecked(True)
        self.tagFilterbutton.setObjectName("tagFilterbutton")
        self.pushbuttonGroup = QtWidgets.QButtonGroup(Filter)
        self.pushbuttonGroup.setObjectName("pushbuttonGroup")
        self.pushbuttonGroup.addButton(self.tagFilterbutton)
        self.horizontalLayout.addWidget(self.tagFilterbutton)
        self.imageFilterbutton = QtWidgets.QPushButton(Filter)
        self.imageFilterbutton.setAutoFillBackground(False)
        self.imageFilterbutton.setStyleSheet("QPushButton {\n"
"    background-color: #34352f;\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"    width: 150px;\n"
"    height:40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #272822;\n"
"}")
        self.imageFilterbutton.setCheckable(True)
        self.imageFilterbutton.setObjectName("imageFilterbutton")
        self.pushbuttonGroup.addButton(self.imageFilterbutton)
        self.horizontalLayout.addWidget(self.imageFilterbutton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.filter_label = QtWidgets.QLabel(Filter)
        self.filter_label.setObjectName("filter_label")
        self.verticalLayout_3.addWidget(self.filter_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filtertable = QtWidgets.QTableWidget(Filter)
        self.filtertable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.filtertable.setColumnCount(1)
        self.filtertable.setObjectName("filtertable")
        self.filtertable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filtertable.setHorizontalHeaderItem(0, item)
        self.filtertable.horizontalHeader().setVisible(True)
        self.filtertable.horizontalHeader().setCascadingSectionResizes(True)
        self.filtertable.horizontalHeader().setSortIndicatorShown(True)
        self.filtertable.horizontalHeader().setStretchLastSection(True)
        self.filtertable.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.filtertable)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.filter_add = QtWidgets.QPushButton(Filter)
        self.filter_add.setObjectName("filter_add")
        self.verticalLayout_4.addWidget(self.filter_add)
        self.filter_del = QtWidgets.QPushButton(Filter)
        self.filter_del.setObjectName("filter_del")
        self.verticalLayout_4.addWidget(self.filter_del)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.filter_useBlacklist = QtWidgets.QRadioButton(Filter)
        self.filter_useBlacklist.setChecked(True)
        self.filter_useBlacklist.setObjectName("filter_useBlacklist")
        self.radiobuttonGroup = QtWidgets.QButtonGroup(Filter)
        self.radiobuttonGroup.setObjectName("radiobuttonGroup")
        self.radiobuttonGroup.addButton(self.filter_useBlacklist)
        self.verticalLayout_4.addWidget(self.filter_useBlacklist)
        self.filter_useWhitelist = QtWidgets.QRadioButton(Filter)
        self.filter_useWhitelist.setObjectName("filter_useWhitelist")
        self.radiobuttonGroup.addButton(self.filter_useWhitelist)
        self.verticalLayout_4.addWidget(self.filter_useWhitelist)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.filter_ok = QtWidgets.QPushButton(Filter)
        self.filter_ok.setObjectName("filter_ok")
        self.verticalLayout_4.addWidget(self.filter_ok)
        self.filter_cancel = QtWidgets.QPushButton(Filter)
        self.filter_cancel.setObjectName("filter_cancel")
        self.verticalLayout_4.addWidget(self.filter_cancel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Filter)
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        _translate = QtCore.QCoreApplication.translate
        Filter.setWindowTitle(_translate("Filter", "过滤器"))
        self.tagFilterbutton.setText(_translate("Filter", "标签过滤"))
        self.imageFilterbutton.setText(_translate("Filter", "图片过滤"))
        self.filter_label.setText(_translate("Filter", "TextLabel"))
        item = self.filtertable.horizontalHeaderItem(0)
        item.setText(_translate("Filter", "英文标签"))
        self.filter_add.setText(_translate("Filter", "添加"))
        self.filter_del.setText(_translate("Filter", "删除"))
        self.filter_useBlacklist.setText(_translate("Filter", "黑名单"))
        self.filter_useWhitelist.setText(_translate("Filter", "白名单"))
        self.filter_ok.setText(_translate("Filter", "确认"))
        self.filter_cancel.setText(_translate("Filter", "取消"))
