# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkingFlowWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkingFlow(object):
    def setupUi(self, WorkingFlow):
        WorkingFlow.setObjectName("WorkingFlow")
        WorkingFlow.resize(545, 556)
        WorkingFlow.setMinimumSize(QtCore.QSize(75, 36))
        WorkingFlow.setStyleSheet("* {\n"
"    font-family:\"KaiTi\";\n"
"    font-size:28px;\n"
"    color: #F8F8F2;\n"
"}\n"
"\n"
"*::item:hover {\n"
"    background-color: #474844;\n"
"}\n"
"*::item:selected {\n"
"    background-color: #75715E;\n"
"}\n"
"\n"
"/* 背景 */\n"
"QWidget {\n"
"    background-color: #202120;\n"
"}\n"
"/* list */\n"
"QListWidget {\n"
"    background-color: #272822;\n"
"    border: none;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"/* table */\n"
"QTableWidget {\n"
"    background-color: #272822;\n"
"    border: none;\n"
"}\n"
"/* table:表头 */\n"
"QHeaderView::section {\n"
"    background-color: #272822;\n"
"}\n"
"/* tooltip:提示 */\n"
"QToolTip {\n"
"    color: #546E7A;\n"
"    fonte: 18px \"SimHei\";\n"
"}\n"
"/* 按钮 */\n"
"QPushButton {\n"
"    background-color: #75715e;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8d8871;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #8d8871;\n"
"}\n"
"/* 编辑栏 */\n"
"QLineEdit {\n"
"    border: 1px solid #99947c; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    background-color: #414339; /* 背景颜色 */\n"
"    color: #cccccc; /* 文本颜色 */\n"
"    selection-background-color: #646765; /* 选中文本的背景颜色 */\n"
"    selection-color: #cccccc; /* 选中文本的颜色 */\n"
"\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #202120;\n"
"    background-color: #202120;\n"
"    color: #F8F8F2;\n"
"}\n"
"\n"
"/* 多页Tab */\n"
"QTabBar::tab {\n"
"    background-color: #34352f;\n"
"    margin-right:1px;\n"
"    margin-left:1px;\n"
"    width:150px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #272822;\n"
"}\n"
"QTabWidget::pane{\n"
"    border:none;\n"
"}\n"
"/* 状态条 */\n"
"QStatusBar {\n"
"    background-color: #414339;\n"
"}\n"
"/* 菜单栏 */\n"
"QMenuBar, QMenu {\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"}\n"
"QMenuBar::item:disabled, QMenu::item:disabled {\n"
"    color: #4c4d4b;\n"
"}\n"
"/* 滑动条 */\n"
"QScrollBar:disabled {\n"
"    background: #272822;\n"
"}\n"
"QScrollBar:vertical {\n"
"    width: 8px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    height: 8px;\n"
"}\n"
"QScrollBar::handle { \n"
"    padding: 0;\n"
"    margin: 2px;\n"
"    border-radius: 2px;\n"
"    border: 2px solid palette(midlight);\n"
"    background: palette(midlight);\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    min-height: 20px;\n"
"    min-width: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    min-width: 20px;\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    border-color: palette(light);\n"
"    background: palette(light);\n"
"}\n"
"QScrollBar::handle:pressed {\n"
"    background: palette(highlight);\n"
"    border-color: palette(highlight);\n"
"}\n"
"QScrollBar::add-line , QScrollBar::sub-line {\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WorkingFlow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wf_editmode = QtWidgets.QPushButton(WorkingFlow)
        self.wf_editmode.setStyleSheet("QPushButton {\n"
"    background-color: #34352f;\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"    width: 150px;\n"
"    height:40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #272822;\n"
"}")
        self.wf_editmode.setCheckable(True)
        self.wf_editmode.setChecked(True)
        self.wf_editmode.setObjectName("wf_editmode")
        self.buttonGroup = QtWidgets.QButtonGroup(WorkingFlow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.wf_editmode)
        self.horizontalLayout_3.addWidget(self.wf_editmode)
        self.wf_workmode = QtWidgets.QPushButton(WorkingFlow)
        self.wf_workmode.setStyleSheet("QPushButton {\n"
"    background-color: #34352f;\n"
"    font-family:\"SimHei\";\n"
"    font-size:25px;\n"
"    color: #F8F8F2;\n"
"    width: 150px;\n"
"    height:40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:selected {\n"
"    background-color: #34352f;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #272822;\n"
"}")
        self.wf_workmode.setCheckable(True)
        self.wf_workmode.setObjectName("wf_workmode")
        self.buttonGroup.addButton(self.wf_workmode)
        self.horizontalLayout_3.addWidget(self.wf_workmode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.wf_insEdit = QtWidgets.QLineEdit(WorkingFlow)
        self.wf_insEdit.setEnabled(True)
        self.wf_insEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.wf_insEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.wf_insEdit.setObjectName("wf_insEdit")
        self.verticalLayout_2.addWidget(self.wf_insEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wf_table = QtWidgets.QTableWidget(WorkingFlow)
        self.wf_table.setObjectName("wf_table")
        self.wf_table.setColumnCount(2)
        self.wf_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wf_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wf_table.setHorizontalHeaderItem(1, item)
        self.wf_table.horizontalHeader().setCascadingSectionResizes(True)
        self.wf_table.horizontalHeader().setSortIndicatorShown(True)
        self.wf_table.horizontalHeader().setStretchLastSection(True)
        self.wf_table.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.wf_table)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wf_delpage = QtWidgets.QPushButton(WorkingFlow)
        self.wf_delpage.setMinimumSize(QtCore.QSize(36, 36))
        self.wf_delpage.setMaximumSize(QtCore.QSize(36, 36))
        self.wf_delpage.setObjectName("wf_delpage")
        self.horizontalLayout.addWidget(self.wf_delpage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.wf_homepage = QtWidgets.QPushButton(WorkingFlow)
        self.wf_homepage.setMinimumSize(QtCore.QSize(65, 36))
        self.wf_homepage.setMaximumSize(QtCore.QSize(65, 36))
        self.wf_homepage.setObjectName("wf_homepage")
        self.horizontalLayout.addWidget(self.wf_homepage)
        self.wf_prepage = QtWidgets.QPushButton(WorkingFlow)
        self.wf_prepage.setMinimumSize(QtCore.QSize(65, 36))
        self.wf_prepage.setMaximumSize(QtCore.QSize(65, 36))
        self.wf_prepage.setAutoDefault(False)
        self.wf_prepage.setObjectName("wf_prepage")
        self.horizontalLayout.addWidget(self.wf_prepage)
        self.wf_pageShow = QtWidgets.QLineEdit(WorkingFlow)
        self.wf_pageShow.setEnabled(False)
        self.wf_pageShow.setMinimumSize(QtCore.QSize(75, 36))
        self.wf_pageShow.setMaximumSize(QtCore.QSize(75, 36))
        self.wf_pageShow.setObjectName("wf_pageShow")
        self.horizontalLayout.addWidget(self.wf_pageShow)
        self.wf_nextpage = QtWidgets.QPushButton(WorkingFlow)
        self.wf_nextpage.setMinimumSize(QtCore.QSize(65, 36))
        self.wf_nextpage.setMaximumSize(QtCore.QSize(65, 36))
        self.wf_nextpage.setObjectName("wf_nextpage")
        self.horizontalLayout.addWidget(self.wf_nextpage)
        self.wf_lastpage = QtWidgets.QPushButton(WorkingFlow)
        self.wf_lastpage.setMinimumSize(QtCore.QSize(65, 36))
        self.wf_lastpage.setMaximumSize(QtCore.QSize(65, 36))
        self.wf_lastpage.setObjectName("wf_lastpage")
        self.horizontalLayout.addWidget(self.wf_lastpage)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.wf_insertpage = QtWidgets.QPushButton(WorkingFlow)
        self.wf_insertpage.setMinimumSize(QtCore.QSize(36, 36))
        self.wf_insertpage.setMaximumSize(QtCore.QSize(36, 36))
        self.wf_insertpage.setObjectName("wf_insertpage")
        self.horizontalLayout.addWidget(self.wf_insertpage)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(WorkingFlow)
        QtCore.QMetaObject.connectSlotsByName(WorkingFlow)

    def retranslateUi(self, WorkingFlow):
        _translate = QtCore.QCoreApplication.translate
        WorkingFlow.setWindowTitle(_translate("WorkingFlow", "工作流"))
        self.wf_editmode.setText(_translate("WorkingFlow", "编辑模式"))
        self.wf_workmode.setText(_translate("WorkingFlow", "工作模式"))
        self.wf_insEdit.setText(_translate("WorkingFlow", "<分组名称>"))
        item = self.wf_table.horizontalHeaderItem(0)
        item.setText(_translate("WorkingFlow", "英文标签"))
        item = self.wf_table.horizontalHeaderItem(1)
        item.setText(_translate("WorkingFlow", "中文标签"))
        self.wf_delpage.setToolTip(_translate("WorkingFlow", "删除当前页"))
        self.wf_delpage.setText(_translate("WorkingFlow", "-"))
        self.wf_homepage.setText(_translate("WorkingFlow", "首页"))
        self.wf_prepage.setText(_translate("WorkingFlow", "←"))
        self.wf_pageShow.setText(_translate("WorkingFlow", "1/1"))
        self.wf_nextpage.setToolTip(_translate("WorkingFlow", "下一页"))
        self.wf_nextpage.setText(_translate("WorkingFlow", "→"))
        self.wf_lastpage.setText(_translate("WorkingFlow", "尾页"))
        self.wf_insertpage.setToolTip(_translate("WorkingFlow", "插入新的页"))
        self.wf_insertpage.setText(_translate("WorkingFlow", "+"))
